# Generated by Django 4.2.16 on 2024-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
